blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs"""
from django.urls import path
from . import views

from django.views.generic import TemplateView

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page for adding a new blog
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for editting an entry.
    path('edit_blogpost/<int:blog_id>/', views.edit_blogpost, name='edit_blogpost'),
    # not allow
    # path('blogs/not_allow/', views.index, name='not_allow')
    path('not_allow', TemplateView.as_view(template_name='not_allow.html'), name='not_allow'),
]

users/urls.py
"""Defines URL patterns for users"""
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registeration page.
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class BlogPost(models.Model):
    """A Blog user post"""
    title = models.CharField(max_length=200)
    text = models.TextField(max_length=400)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """"""
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['text', 'title']
        # labels = {'text':'', 'title':''}

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import BlogPost
from .forms import BlogPostForm




# Create your views here.
def index(request):
    """The home page for blogs"""
    blogs = BlogPost.objects.order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/index.html', context)


@login_required
def new_blog(request):
    """Add a new blog."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogPostForm()
    else:
        # POST data submitted; process data.
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')    # redirect to home page

    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


@login_required
def edit_blogpost(request, blog_id):
    """Edit an existing blog."""

    blog = BlogPost.objects.get(id=blog_id)
    if blog.owner == request.user:
        if request.method != 'POST':
            # Initial request; pre-fill form with the current blog.
            form = BlogPostForm(instance=blog)
        else:
            # POST data submitted; process data.
            form = BlogPostForm(instance=blog, data=request.POST)
            if form.is_valid():
                form.save()
                return redirect('blogs:index')

        context = {'blog': blog, 'form': form}
        return render(request, 'blogs/edit_blogpost.html', context)
    else:
        return redirect('blogs:not_allow')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')
    # Display a blank or invalid form
    context = {'form':form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
<p>
    <a href="{% url 'blogs:index' %}">Blogs</a>

    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a> -
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %}

blogs/templates/blogs/edit_blogpost.html
{% extends "blogs/base.html" %}

{% block content %}

    <p>Edit blogpost:</p>

    <form action="{% url 'blogs:edit_blogpost' blog.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
<p>below are posts</p>
<ul>

    {% for blog in blogs %}

    <li><p>{{blog.title}} -- {{blog.date_added|date:'M d, Y H:i'}}</p></li>
        <p>{{blog.text|linebreaks}}</p>
        <p>
            <a href="{% url 'blogs:edit_blogpost' blog.id %}">Edit Blog</a>
        </p>
        </p>
    {% empty %}
        <li>No blog now</li>
    {% endfor %}
</ul>

<a href="{% url 'blogs:new_blog' %}">Add a new blog</a>

{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>Add a new blog</p>

    <form action="{% url 'blogs:new_blog' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="Sumbit">Add blog</button>
    </form>

{% endblock content %}

blogs/templates/not_allow.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>you are not allowed to do so</p>
	<p><a href="{% url 'blogs:index' %}">go back to home</a></p>
{% endblock content %}